### ISSUE TITLE
re-registration of query weighting function results in out-of-memory

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strusWebService#51]
```
2016-06-20 09:24:27; strusWebService, warning: registering weighting function 'test'
resulted in an error: error in database transaction commit: database transaction
with error: memory allocation error (strusContext.cpp:65)
```

Actually this looks more like memory corruption to me.

Besides, this should be fixed by changing the way we handle functions loaded from
modules. We should not load them on every query request.

**Comment by andreasbaumann** [comment]
Also seen while inserting: the query works ok, but a message about a commit memory error
appear underneath:

```
2016-07-13 08:05:06; strusWebService, warning: 
registering weighting function 'test' resulted in an error: 
storage transaction with error: 
storage transaction with error: storage transaction with error: 
storage transaction with error: storage transaction with error: 
storage transaction with error: storage transaction with error: 
storage transaction with error: storage transaction with error: 
storage transaction with error: storage transaction with error: 
error in database transaction commit: 
database transaction with error: memory allocation error (strusContext.cpp:65)
```

Inserting seems to run fine though.
Maybe a transaction run  into memory problems before?
Maybe the buffer still contains a error messages from before?

**Comment by andreasbaumann** [comment]
This error happens when printing a message with a pointer to a format string used as argument.
The implementation of the ErrorBufferInterface should print an error first with snprintf to a local buffer,
before copying it into the thread-global buffer.

**Comment by andreasbaumann** [comment]
See https://github.com/patrickfrey/strusBase/blob/master/src/error/errorBuffer.cpp line 32-40

**Comment by andreasbaumann** [comment]
Is this fixed in strusBase or do I have to do something?

**Comment by patrickfrey** [comment]
It has been fixed in strusBase
